# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'E-Market Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for E-Market Demo
pod 'Kingfisher'

  target 'E-Market DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'E-Market DemoUITests' do
    # Pods for testing
  end

end
